import { IllegalStateTransitionError } from '@/lib/errors';

export const APPROVAL_STATUS = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  ASSIGNED: 'ASSIGNED',
  REVIEWED: 'REVIEWED',
  ESCALATED: 'ESCALATED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  RETURNED_FOR_CORRECTION: 'RETURNED_FOR_CORRECTION',
} as const;

export const EXCEPTION_STATUS = {
  OPEN: 'OPEN',
  TRIAGED: 'TRIAGED',
  ASSIGNED: 'ASSIGNED',
  INVESTIGATING: 'INVESTIGATING',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
  REOPENED: 'REOPENED',
} as const;

export const SUBMISSION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REQUIRES_CHANGES: 'REQUIRES_CHANGES',
  RESUBMITTED: 'RESUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ARCHIVED: 'ARCHIVED',
} as const;

const APPROVAL_TRANSITIONS: Record<string, ReadonlySet<string>> = {
  PENDING: new Set(['ACTIVE', 'REVOKED', APPROVAL_STATUS.PENDING_REVIEW]),
  ACTIVE: new Set(['EXHAUSTED', 'EXPIRED', 'REVOKED', APPROVAL_STATUS.REVIEWED]),
  EXPIRED: new Set([]),
  REVOKED: new Set([]),
  EXHAUSTED: new Set([]),
  [APPROVAL_STATUS.PENDING_REVIEW]: new Set([APPROVAL_STATUS.ASSIGNED, APPROVAL_STATUS.REJECTED]),
  [APPROVAL_STATUS.ASSIGNED]: new Set([APPROVAL_STATUS.REVIEWED, APPROVAL_STATUS.ESCALATED, APPROVAL_STATUS.RETURNED_FOR_CORRECTION]),
  [APPROVAL_STATUS.REVIEWED]: new Set([APPROVAL_STATUS.APPROVED, APPROVAL_STATUS.REJECTED, APPROVAL_STATUS.ESCALATED]),
  [APPROVAL_STATUS.ESCALATED]: new Set([APPROVAL_STATUS.REVIEWED, APPROVAL_STATUS.REJECTED]),
  [APPROVAL_STATUS.APPROVED]: new Set([]),
  [APPROVAL_STATUS.REJECTED]: new Set([]),
  [APPROVAL_STATUS.RETURNED_FOR_CORRECTION]: new Set([APPROVAL_STATUS.PENDING_REVIEW]),
};

const EXCEPTION_TRANSITIONS: Record<string, ReadonlySet<string>> = {
  OPEN: new Set(['UNDER_REVIEW', EXCEPTION_STATUS.TRIAGED, EXCEPTION_STATUS.DISMISSED]),
  UNDER_REVIEW: new Set(['RESOLVED', 'WAIVED', EXCEPTION_STATUS.INVESTIGATING]),
  RESOLVED: new Set(['OPEN', EXCEPTION_STATUS.REOPENED]),
  WAIVED: new Set([EXCEPTION_STATUS.REOPENED]),
  [EXCEPTION_STATUS.TRIAGED]: new Set([EXCEPTION_STATUS.ASSIGNED, EXCEPTION_STATUS.DISMISSED]),
  [EXCEPTION_STATUS.ASSIGNED]: new Set([EXCEPTION_STATUS.INVESTIGATING, EXCEPTION_STATUS.REOPENED]),
  [EXCEPTION_STATUS.INVESTIGATING]: new Set([EXCEPTION_STATUS.RESOLVED, EXCEPTION_STATUS.DISMISSED]),
  [EXCEPTION_STATUS.RESOLVED]: new Set([EXCEPTION_STATUS.REOPENED]),
  [EXCEPTION_STATUS.DISMISSED]: new Set([EXCEPTION_STATUS.REOPENED]),
  [EXCEPTION_STATUS.REOPENED]: new Set([EXCEPTION_STATUS.INVESTIGATING, EXCEPTION_STATUS.ASSIGNED]),
};

export function assertValidApprovalTransition(from: string, to: string): void {
  const allowed = APPROVAL_TRANSITIONS[from] ?? new Set<string>();
  if (!allowed.has(to)) {
    throw new IllegalStateTransitionError('approval', from, to);
  }
}

export function assertValidExceptionTransition(from: string, to: string): void {
  const allowed = EXCEPTION_TRANSITIONS[from] ?? new Set<string>();
  if (!allowed.has(to)) {
    throw new IllegalStateTransitionError('exception', from, to);
  }
}
